delete from employees;
delete from messages;
delete from product_categories;
delete from products;
delete from reviews;


insert into employees (  id,
                       name,
                       job,
                       description,
                       img,
                       created_at,
                       updated_at)
values (1,
        'Julie',
        'Barista',
        'Daniel travaille depuis 2019 chez nous.',
        './images/team/smiley-business-woman-working-cashier.jpg',
        '2019-08-27',
        sysdate()),
        (2,
        'Anna',
        'Barista',
        'Anna est une personne très joyeuse et travaille depuis 2021 chez nous.',
        './images/team/cute-korean-barista-girl-pouring-coffee-prepare-filter-batch-brew-pour-working-cafe.jpg',
        '2021-11-20',
        sysdate()),
        (3,
        'Frederico',
        'Manager',
        'Frederico travaille depuis 2015 chez nous.',
        './images/team/small-business-owner-drinking-coffee.jpg',
        '2015-04-17',
        sysdate()),
        (4,
        'David',
        'Propriétaire',
        'David a ouvert Chocolatte en 2013.',
        './images/team/portrait-elegant-old-man-wearing-suit.jpg',
        '2013-08-27',
        sysdate());


insert into messages (id, name, email, content, created_at, updated_at)
values ('1',
        'Véronique',
        'véroniquedupont@gmail.be',
        'J’ai bien aimé le service de votre établissement.',
        '2017-04-26',
        sysdate()),
        ('2',
        'Jean',
        'jeanJaques@gmail.be',
        'Je veux commander un bon cadeau pour ma femme.',
        '2018-09-06',
        sysdate()),
        ('3',
        'Amélie',
        'Amelie123@gmail.be',
        'Je veux bien précommander un cadeau de chocolat et café pour ma copine qui aura 25 ans cette année.',
        '2021-07-01',
        sysdate()),
        ('4',
        'Brigitte',
        'brigittepaquet@gmail.be',
        'Je me plains de la qualité du café. Il n’y avait pas de lait quand j’étais là.',
        '2023-02-26',
        sysdate());


insert into product_categories( id,
                                parent_id,
                                order,
                                pre,
                                title,
                                created_at,
                                updated_at)
values ( '1',
         'Déjeuner',
         '1',
         'Déjeuner délicieux',
        'Déjeuner',
        '2015-09-03',
        sysdate()),
    ( '1',
         'Déjeuner',
         '2',
         'Coffee lovers',
        'Café',
        '2015-09-03',
        sysdate());

insert into products(id,
                     product_category_id,
                    name,
                    description,
                    tag,
                    price,
                    discount,
                    created_at,
                    updated_at,
                    deleted_at)
values ('1',
        'Déjeuner',
        'Pancake',
        'deux pancake avec de la confiture de fraises et un café.',
        '',
        '7.35€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
        ('2',
        'Déjeuner',
        'Croissant-fraise',
        'Un croissant avec du beurre et de la confiture de fraises.',
        'recommend',
        '5.30€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
         ('3',
        'Déjeuner',
        'Banana Cake',
        'Un morceau de tarte aux bananes avec un café.',
        '',
        '6.99€',
        '5.00€',
        '2015-01-05',
        sysdate(),
        ''),
        ('4',
        'Café',
        'Latte',
        'Un café avec du lait.',
        'recommend',
        '5.15€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
         ('5',
        'Café',
        'Chocolat chaud',
        'Un chocolat chaud avec du des bisquits et du chantilly.',
        'recommend',
        '5.99€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
          ('6',
        'Café',
        'Thée vert',
        'Un thé vert avec du lait et des bisquits.',
        '',
        '6.55€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
           ('7',
        'Déjeuner',
        'Pain fromage et pain jambon',
        'Un Pain fromage et un pain jambon frais .',
        'recommend',
        '9.99€',
        '',
        '2015-01-05',
        sysdate(),
        ''),
            ('8',
        'Déjeuner',
        'Pain au chocolat et pain au jambon',
        'Un pain au chocolat avec un petit pain au jambon.',
        'recommend',
        '9.99€',
        '7.99€',
        '2015-01-05',
        sysdate(),
        '');



insert into reviews (id,
                    customer,
                    cover_img,
                    avatar_img,
                    content,
                    rating,
                    certified_at,
                    created_at,
                    updated_at)
values ('1',
        'Véronique',
        './images/slides/mid-section-waitress-wiping-espresso-machine-with-napkin-cafa-c.jpg',
        'young-woman-with-round-glasses-yellow-sweater.jpg',
        'J’ai bien aimé le service de votre établissement.',
        '4',
        '2023-07-09',
        '2023-07-08',
        sysdate()),
        ('2',
        'Amélie',
        './images/slides/mid-section-waitress-wiping-espresso-machine-with-napkin-cafa-c.jpg',
        'young-beautiful-woman-pink-warm-sweater-natural-look-smiling-portrait-isolated-long-hair.jpg',
        'L‘ambiance est bonne et le patron est très sympa.',
        '5',
        '2021-04-05',
        '2023-04-04',
        sysdate()),
        ('3',
        'Jean',
        './images/slides/mid-section-waitress-wiping-espresso-machine-with-napkin-cafa-c.jpg',
        'senior-man-white-sweater-eyeglasses.jpg',
        'J’ai mangé très bien ici. Le personnel est sympa et très attentif. La décoration est bien faite et les produits sont frais.',
        '4.5',
        '2018-02-26',
        '2018-02-25',
        sysdate());


commit;
